version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: fashion_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./storage/qdrant:/qdrant/storage   # Đã di chuyển từ ./qdrant_storage
    restart: always

  redis:
    image: redis/redis-stack:latest
    container_name: fashion_redis_stack
    ports:
      - "6379:6379"   # Port kết nối database
      - "8001:8001"   # Port giao diện web RedisInsight
    volumes:
      - ./storage/redis:/data              # Đã di chuyển từ ./redis_data
    restart: always